name:                theory-engine
version:             0.1.0.0
github:              "mitchwagner/theory-engine"
license:             MIT 
author:              "Mitchell James Wagner"
maintainer:          "mitchell.j.wagner@gmail.com"
copyright:           "2020 Mitchell James Wagner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/mitchwagner/theory-engine#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  theory-engine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - theory-engine

tests:
  theory-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - theory-engine
